### PR TITLE
chore: remove test-only getters

### PR DESCRIPTION
**Pull request by mootz12**
Saves about 1kB on Pool and 500 bytes on Backstop.

Seeing as I don't really see how these functions would be useful for contracts, it feels better to remove them now.

It will be easier to add back a getter in the future than it will be to remove them.

### CODE REVIEW

**Review by markuspluna — APPROVED** [review]
lgtm - agree with all the cuts

**Review by Ryang-21 — APPROVED** [review]
lgtm

**Comment by mootz12** [comment]
Renamed:
* backstop-module -> backstop
* lending-pool -> pool

Added:
* i128 return value for backstop claim function
* `blend-interfaces` package for dependent contracts

cc: @markuspluna @Ryang-21

**Review by Ryang-21 — APPROVED** [review]
lgtm

**Pull request merged**
